# Generated by Django 6.0.3 on 2026-03-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="loja",
            name="morada",
        ),
        migrations.RemoveField(
            model_name="morada",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="tipo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="morada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="loja.morada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="loja.cliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="loja",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="loja.loja",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="morada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="pedidos",
                to="loja.morada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="numeroPedido",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produtos",
                to="loja.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="pedido",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produtos",
                to="loja.pedido",
            ),
            preserve_default=False,
        ),
    ]
