# Generated by Django 6.0.3 on 2026-03-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacaoDoQuiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bandas",
            new_name="Banda",
        ),
    ]
