# Generated by Django 6.0.3 on 2026-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilizador",
            name="receita",
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "receita",
                    models.ManyToManyField(
                        related_name="ingredientes", to="receita.receita"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Ingredientes",
        ),
        migrations.AddField(
            model_name="utilizador",
            name="receita",
            field=models.ManyToManyField(
                related_name="utilizadores", to="receita.receita"
            ),
        ),
    ]
