# Generated by Django 6.0.3 on 2026-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0002_remove_utilizador_receita_ingrediente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingrediente",
            name="receita",
        ),
        migrations.AddField(
            model_name="receita",
            name="ingrediente",
            field=models.ManyToManyField(
                related_name="receitas", to="receita.ingrediente"
            ),
        ),
    ]
