# Generated by Django 6.0.3 on 2026-03-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="turma",
            old_name="nome",
            new_name="ano",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="idade",
        ),
    ]
