# Generated by Django 6.0.3 on 2026-03-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ginasio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membro",
            name="personalTrainer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membros",
                to="ginasio.personaltrainer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sessao",
            name="ginasio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessoes",
                to="ginasio.ginasio",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personaltrainer",
            name="ginasio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personaltrainers",
                to="ginasio.ginasio",
            ),
        ),
    ]
