# Generated by Django 6.0.3 on 2026-04-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("soft", "Soft Skill"),
                            ("lingua", "Língua"),
                            ("outra", "Outra"),
                        ],
                        default="tecnica",
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Inicial"),
                            (2, "Básico"),
                            (3, "Intermédio"),
                            (4, "Bom"),
                            (5, "Muito Bom"),
                        ],
                        default=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("pagina_pessoal", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=20)),
                ("descricao", models.TextField(blank=True)),
                ("duracao", models.PositiveIntegerField(blank=True, null=True)),
                ("ects", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="licenciaturas/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("data", models.DateField()),
                ("objeto_nome", models.CharField(blank=True, max_length=150)),
                ("descricao_processo", models.TextField()),
                ("decisao_tomada", models.TextField(blank=True)),
                ("erro_encontrado", models.TextField(blank=True)),
                ("correcao", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("usei_ai", models.BooleanField(default=False)),
                ("como_usei_ai", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField(blank=True)),
                ("git_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("data", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("entidade", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("academica", "Académica"),
                            ("curso", "Curso"),
                            ("certificacao", "Certificação"),
                            ("workshop", "Workshop"),
                            ("outra", "Outra"),
                        ],
                        default="curso",
                        max_length=20,
                    ),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("duracao", models.CharField(blank=True, max_length=60)),
                ("certificado_url", models.URLField(blank=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="formacoes/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.projeto"
            ),
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("website", models.URLField(blank=True)),
                ("nivel_preferencia", models.PositiveSmallIntegerField(default=3)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tecnologias",
                        to="portfolio.categoriatecnologia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=120)),
                ("ano", models.PositiveIntegerField(blank=True, null=True)),
                ("resumo", models.TextField(blank=True)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(blank=True)),
                ("nivel_interesse", models.PositiveSmallIntegerField(default=3)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=30)),
                ("ano", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("semestre", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ects", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
