# Generated by Django 6.0.3 on 2026-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="entidade_alvo",
            field=models.CharField(
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("docente", "Docente"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("tfc", "TFC"),
                    ("competencia", "Competência"),
                    ("formacao", "Formação"),
                    ("geral", "Geral"),
                ],
                default="geral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="justificacao",
            field=models.TextField(blank=True),
        ),
    ]
